
DROP SCHEMA IF EXISTS GREETING;
CREATE SCHEMA GREETING;


DROP SEQUENCE  IF EXISTS GREETING.REQUEST_ID;
CREATE SEQUENCE GREETING.REQUEST_ID ;

DROP TABLE IF EXISTS GREETING.REQUESTS;

CREATE TABLE GREETING.REQUESTS (
  REQUEST_ID INTEGER NOT NULL,
  GREET_TO VARCHAR(20) NOT NULL DEFAULT 'unknown',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);