
DROP SCHEMA IF EXISTS GREETING;
CREATE SCHEMA GREETING;

DROP TABLE IF EXISTS GREETING.REQUESTS;

CREATE TABLE GREETING.REQUESTS (
  ID INTEGER NOT NULL,
  NAME VARCHAR(20) NOT NULL DEFAULT 'unknown',
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);